# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New', '0003_auto_20171011_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcontains',
            name='RIDs',
        ),
        migrations.RemoveField(
            model_name='mcontains',
            name='Snacks',
        ),
        migrations.RemoveField(
            model_name='rcontains',
            name='IIDS',
        ),
        migrations.AddField(
            model_name='meals',
            name='RIDs',
            field=models.ManyToManyField(to='New.Recipes'),
        ),
        migrations.AddField(
            model_name='meals',
            name='Snacks',
            field=models.ManyToManyField(to='New.Ingredient'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='IIDS',
            field=models.ManyToManyField(to='New.Ingredient'),
        ),
        migrations.DeleteModel(
            name='Mcontains',
        ),
        migrations.DeleteModel(
            name='Rcontains',
        ),
    ]
