# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='static/pictures/UserPhoto/default-user.png', upload_to='static/pictures/UserPhoto/'),
        ),
    ]
