# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pubDate', models.DateTimeField(verbose_name=b'date published')),
                ('author', models.CharField(max_length=60)),
                ('rate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pubDate', models.DateTimeField(verbose_name=b'date published')),
                ('author', models.CharField(max_length=60)),
                ('rate', models.CharField(max_length=20)),
            ],
        ),
    ]
