# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 02:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schema', '0002_auto_20171013_0151'),
    ]

    operations = [
    ]
