# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 02:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0003_auto_20171019_0235'),
    ]

    operations = [
    ]
