# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0006_auto_20171019_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='like_recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('recipeName', models.CharField(max_length=50)),
            ],
        ),
    ]
