# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 21:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schema', '0008_auto_20171102_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='contain_tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schema.Recipes')),
            ],
        ),
        migrations.CreateModel(
            name='Recipes_tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='like_recipe',
            name='recipeName',
        ),
        migrations.RemoveField(
            model_name='like_recipe',
            name='userName',
        ),
        migrations.AddField(
            model_name='like_recipe',
            name='r_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schema.Recipes'),
        ),
        migrations.AddField(
            model_name='like_recipe',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contain_tag',
            name='t_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schema.Recipes_tag'),
        ),
    ]
