# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0010_auto_20171105_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
