# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0011_auto_20171105_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes_HitCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hitcount', models.IntegerField(default=0)),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schema.Recipes')),
            ],
        ),
    ]
